listener {
    # Prima che il sistema vada in sleep (Sospensione), lancia hyprlock
    on-timeout = echo "In attesa"
    on-resume = echo "Sveglio"
}

general {
    # Il comando cruciale per eliminare il glitch al risveglio
    before_sleep_cmd = hyprlock
}
