# ==========================================
# CONFIGURAZIONE HYPRLOCK ISTANTANEA
# ==========================================

background {
    monitor =
    # Metti qui il percorso del tuo sfondo fisso
    path = /usr/share/backgrounds/archlinux/archwave.png
    color = rgba(17, 17, 17, 1.0)

    # Se vuoi l'effetto sfocato perfetto della GPU, scommenta queste due righe:
    # blur_passes = 2
    # blur_size = 7
}

# --- OROLOGIO ---
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(255, 255, 255, 1.0)
    font_size = 55
    font_family = Cantarell
    position = 0, 150
    halign = center
    valign = center
}

# --- INPUT PASSWORD (CERCHIO NEON) ---
input-field {
    monitor =
    size = 220, 50
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    
    # Colori stile Cyberpunk
    outer_color = rgba(0, 255, 204, 1.0) # Azzurro Neon fisso
    inner_color = rgba(17, 17, 17, 0.6)
    font_color = rgba(255, 255, 255, 1.0)
    
    # Quando digiti la password
    check_color = rgba(255, 0, 127, 1.0) # Rosa Neon in digitazione
    
    # Quando sbagli la password
    fail_color = rgba(204, 34, 34, 1.0)
    fail_text = <i>Password errata</i>
    
    position = 0, -50
    halign = center
    valign = center
}
